# Give tmux sessions access to the macOS clipboard.
set-option -g default-command "reattach-to-user-namespace -l $SHELL" 

# vi keys in copy mode
setw -g mode-keys vi

# In iTerm, enable "Applications in terminal may access clipboard" for copying.
bind-key -Tcopy-mode-vi 'v' send -X begin-selection
bind-key -Tcopy-mode-vi 'y' send -X copy-selection

set -g history-limit 50000

# Avoid delaying Escape when leaving Vim insert mode.
set -s escape-time 0

# Use Ctrl-A as the prefix; press it twice to send Ctrl-A to the application.
unbind-key C-b
set -g prefix 'C-a'
bind-key 'C-a' send-prefix


# Vim keys for pane switching
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind R source-file '~/.tmux.conf'
