#!/bin/bash

if [ $# -lt 1 ]; then
    echo "Usage: $(basename "$0") input.flac [output.mp3]" >&2
    exit 1
fi

input="$1"

if [ $# -gt 1 ]; then
    output="$2"
else
    output="${input%.flac}.mp3"
fi

ffmpeg -i "$input" -c:a libmp3lame -b:a 320k "$output" && echo "Converted $input to $output"

