#!/bin/bash

is_active=$(defaults read com.apple.finder CreateDesktop)

if ((is_active))
then
	defaults write com.apple.finder CreateDesktop 0; killall Finder
	echo "Disabled desktop"
fi

if ! ((is_active))
then
	defaults write com.apple.finder CreateDesktop 1; killall Finder
	echo "Enabled desktop"
fi
